url: "http://prrraveen.github.io/wedding-theme" # the base hostname & protocol for your site

markdown: kramdown

include: ['_pages']

# jekyll-sitemap generate sitemap.xml at _site/ dir. It helps google search webmaster to index the website
# jekyll-feed The plugin will automatically generate an Atom feed at /feed.xml.

# HOW TO INSTALL - >  sudo gem install jekyll-sitemap jekyll-feed
gems: [jekyll-sitemap,jekyll-feed,jekyll-paginate,jekyll-archives]

# how many post to show in ALL POST and FEATURED POST
paginate: 6

paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: archive-time
    month: archive-time
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
