url: "http://prrraveen.github.io/wedding-theme" # the base hostname & protocol for your site

markdown: kramdown

include: ['_pages']

# jekyll-sitemap generate sitemap.xml at _site/ dir. It helps google search webmaster to index the website
# jekyll-feed The plugin will automatically generate an Atom feed at /feed.xml.

# HOW TO INSTALL - >  sudo gem install jekyll-sitemap jekyll-feed
gems: [jekyll-sitemap,jekyll-feed,github-pages]
